import type { Task } from "./types";

function inDays(days: number, hour = 17): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const SAMPLE_TASKS: Task[] = [
  {
    id: "t1",
    subject: "Calculus II",
    title: "Midterm exam — integration techniques",
    description: "Revise substitution, parts, partial fractions and improper integrals.",
    deadline: inDays(2, 9),
    difficulty: "Hard",
    hours: 6,
    type: "Exam",
    completed: false,
    createdAt: inDays(-6),
  },
  {
    id: "t2",
    subject: "Physics",
    title: "Lab report — thermodynamics experiment",
    description: "Write up the calorimetry results with error analysis and graphs.",
    deadline: inDays(5, 23),
    difficulty: "Medium",
    hours: 4,
    type: "Project",
    completed: false,
    createdAt: inDays(-4),
  },
  {
    id: "t3",
    subject: "History",
    title: "Reading — Chapter 4: Industrial Revolution",
    description: "Annotate key dates and prepare three discussion points.",
    deadline: inDays(9),
    difficulty: "Easy",
    hours: 1.5,
    type: "Study",
    completed: false,
    createdAt: inDays(-3),
  },
  {
    id: "t4",
    subject: "Chemistry",
    title: "Organic chemistry problem set 6",
    description: "SN1/SN2 mechanisms and stereochemistry problems 1–18.",
    deadline: inDays(1, 12),
    difficulty: "Medium",
    hours: 2.5,
    type: "Assignment",
    completed: false,
    createdAt: inDays(-2),
  },
  {
    id: "t5",
    subject: "Physics",
    title: "Weekly quiz — kinematics",
    description: "Short quiz covering motion graphs and projectiles.",
    deadline: inDays(3, 10),
    difficulty: "Easy",
    hours: 1,
    type: "Quiz",
    completed: false,
    createdAt: inDays(-2),
  },
  {
    id: "t6",
    subject: "Calculus II",
    title: "Series convergence worksheet",
    description: "Ratio and root tests, alternating series.",
    deadline: inDays(-2),
    difficulty: "Medium",
    hours: 2,
    type: "Assignment",
    completed: true,
    createdAt: inDays(-9),
  },
  {
    id: "t7",
    subject: "Chemistry",
    title: "Lab safety module",
    description: "Complete the online safety certification.",
    deadline: inDays(-4),
    difficulty: "Easy",
    hours: 1,
    type: "Study",
    completed: true,
    createdAt: inDays(-10),
  },
  {
    id: "t8",
    subject: "History",
    title: "Essay outline — colonial trade",
    description: "Thesis plus three supporting arguments with sources.",
    deadline: inDays(-1),
    difficulty: "Medium",
    hours: 2,
    type: "Assignment",
    completed: true,
    createdAt: inDays(-8),
  },
];
